FROM ipfs/go-ipfs:release
# FROM golang:1.15.2-buster

# ENV ipfs_staging=/export
# ENV ipfs_data=/data/ipfs



# WORKDIR /myipfs
# RUN cd /myipfs
# # config ipfs
# RUN cd /data/ipfs && ipfs init &&\
#     ipfs config --json API.HTTPHeaders.Access-Control-Allow-Methods '["PUT", "GET", "POST", "OPTIONS"]' &&\
#     ipfs config --json API.HTTPHeaders.Access-Control-Allow-Origin '["*"]'
