version: '3'
services:
  backend:
    build:
      context: ./docker/backend
    # networks:
    #   - db_network
    ports:
      - '3001:3001'
    volumes:
      - ./docker/backend/tmp_files:/backend/tmp_files
      - ./docker/backend/hpcp_data:/backend/hpcp_data

  # python:
  #   build:
  #     context: ./docker/python
  #   volumes:
  #     - .:/code
  #   depends_on:
  #     - db
  #   networks:
  #     - db_network
  # ports:
  #   - "3001:3001"
# networks:
#   db_network:
